language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest pytest-cov coveralls"
script:
  - py.test --cov=repose/
  - coveralls
