language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5-dev"
install:
  - "python setup.py develop"
  - "pip install ."
  - "pip install pytest pytest-cov"
  - pip install --pre $(python -c "import sys; print('coverage>4.0a1 coveralls>=1.0b1' if sys.version_info > (3,3) else 'coverage<4 coveralls<1')")
script:
  - py.test --cov=repose/
  - coveralls
